ExpedienteClinicoProject/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings

@login_required
def index(request):
    return render(request, 'pages/index.html')

urlpatterns = [
    path('',auth_views.LoginView.as_view(template_name='account/prueba.html'), name='login'),
    path('home/', index, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.account.urls')),
    path('clinica/', include('apps.personas.urls'), name='clinica'),
    path('consultas/', include('apps.consultas.urls'), name='consultas'),
    # path('pacientes/', include('apps.personas.urls'), name='pacientes'),
    # path('especialidades/', include('apps.personas.urls'), name='especialidades')
    path('antecedentes/', include('apps.antecedentes.urls'), name='antecedentes'),#☠
    path('laboratorio/', include('apps.examenes.urls'), name='laboratorio')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/antecedentes/urls.py
from django.urls import path, include
from apps.antecedentes.views import (antecedente_familiar_create,
									antecedente_familiar_edit,
									antecedente_familiar_delete,
									antecedente_personal_alergias_edit,
									antecedente_personal_medico_create,
									antecedente_personal_medico_edit,
									antecedente_personal_medico_delete,
									antecedente_personal_quirurgico_create,
									antecedente_personal_quirurgico_edit,
									antecedente_personal_quirurgico_delete,
									antecedente_personal_medicacion_actual_create,
									antecedente_personal_medicacion_actual_edit,
									antecedente_personal_medicacion_actual_delete,
									busqueda_codigo,
									busqueda_enfermedad,
									)

urlpatterns = [

	### URLS QUE MANEJAN LOS ANTECEDENTES ###

	#-- Antecedentes Familiares

	#Crear
	path('familiar/crear/<int:id_paciente>/', antecedente_familiar_create, name='ante_familiar_crear'),#Url para Crear nuevo Antecedente Familiar
	#Editar
	path('familiar/editar/',antecedente_familiar_edit, name='ante_familiar_editar'),
	#Eliminar
	path('familiar/<int:id_antecedente_familiar>/eliminar/',antecedente_familiar_delete, name='ante_familiar_eliminar'),

    ##-- Antecedentes Personal - Alergias (Todo paciente creado ya debe tener una intancia del objeto AntecedentesPersonal)

    #NO POSEE CREAR
	#Editar
	path('personal/alergias/editar/<int:id_paciente>/',antecedente_personal_alergias_edit, name='ante_alergias_editar'),
	#NO POSEE ELIMINAR

    #-- Antecedentes Médicos

    #Crear
    path('personal/medico/crear/<int:id_paciente>/',antecedente_personal_medico_create, name='ante_medico_crear'),
	#Editar
	path('personal/medico/editar/',antecedente_personal_medico_edit, name='ante_medico_editar'),
	#Eliminar
	path('personal/medico/<int:id_antecedente_medico>/eliminar/',antecedente_personal_medico_delete, name='ante_medico_eliminar'),

    #-- Antecedentes Quirúrgico

    #Crear
    path('personal/quirurgico/crear/<int:id_paciente>/',antecedente_personal_quirurgico_create, name='ante_quirurgico_crear'),
	#Editar
	path('personal/quirurgico/editar/',antecedente_personal_quirurgico_edit, name='ante_quirurgico_editar'),
	#Eliminar
	path('personal/quirurgico/<int:id_antecedente_quirurgico>/eliminar/',antecedente_personal_quirurgico_delete, name='ante_quirurgico_eliminar'),

    #-- Medicación Actual

    #Crear
    path('personal/medicacion_actual/crear/<int:id_paciente>/',antecedente_personal_medicacion_actual_create, name='ante_medicacion_crear'),
	#Editar
	path('personal/medicacion_actual/editar/',antecedente_personal_medicacion_actual_edit, name='ante_medicacion_editar'),
	#Eliminar
	path('personal/medicacion_actual/<int:id_medicacion_actual>/eliminar/',antecedente_personal_medicacion_actual_delete, name='ante_medicacion_eliminar'),

	#Para ajax Codigo Internacional
	path('ajax/codigo',busqueda_codigo, name="busqueda_codigo"),
	path('ajax/enfermedad',busqueda_enfermedad, name="busqueda_enfermedad"),
]

apps/antecedentes/models.py
from django.db import models
from apps.personas.models import Paciente
from apps.consultas.models import CodigoInternacional

# Create your models here.
class AntecedentesPersonal(models.Model):
    #id default
    alergias = models.CharField(max_length=500, default='El paciente declaró que no posee alergias.')
    id_paciente = models.OneToOneField(Paciente, on_delete=models.CASCADE,db_column='id_paciente') #Cambio ForeingKey por OneToOne
    #id_medicacion_actual = models.ForeignKey(MedicacionActual, on_delete=models.CASCADE, db_column='id_medicacion_actual') #No se puede cambiar a medicación actual aunque es lo correcto

    class Meta:
        db_table = 'Antecedentes_personal'
        verbose_name = 'Antecedente personal'
        verbose_name_plural = 'Antecedentes personales'
        default_permissions = []

    def __str__(self):
        return '%s' % (self.id)

class AntecedentesMedicos(models.Model):
    #id default
    fecha = models.DateField() #igual definir un estandar con el nombre abreviar o no
    id_antecedentes_personal = models.ForeignKey(AntecedentesPersonal, on_delete=models.CASCADE,db_column='id_antecedentes_personal') # me confundi es el id de antecedentes clinico?
    id_codigo = models.ForeignKey(CodigoInternacional,on_delete=models.CASCADE, db_column='id_codigo') #estandar con llave foranea codigo?


    class Meta:
        db_table = 'Antecedentes_medicos'
        verbose_name = 'Antecedente medico'
        verbose_name_plural = 'Antecedentes medicos'
        default_permissions = []

    def __str__(self):
        return '%s' % (self.id)


class AntecedentesFamiliares(models.Model):
    #id default
    nombre_familiar = models.CharField(max_length=200)
    parentesco = models.CharField(max_length=50)
    padecimientos = models.CharField(max_length=500, blank=True, null=True)
    id_paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, db_column='id_paciente') #Cambio OneToOne por ForeignKey

    class Meta:
        db_table = 'Antecedentes_familiares'
        verbose_name = 'Antecedente familiar'
        verbose_name_plural = 'Antecedentes familiares'
        default_permissions = []

    def __str__(self):
        return '%s' % (self.id)

class AntecedentesQuirurgico(models.Model):
    #id default
    descripcion_cirugia = models.CharField(max_length=500, default='some_string')
    complicacion= models.CharField(max_length=500,blank=True, null=True)
    fecha = models.DateField()
    causa = models.CharField(max_length=500)
    id_antecedentes_personal= models.ForeignKey(AntecedentesPersonal, on_delete=models.CASCADE,db_column='id_antecedentes_personal')#Cambio relacion de OneToOne a ForeingKey

    class Meta:
        db_table = 'Antecedentes_quirurgico'
        verbose_name = 'Antecedente quirurgico'
        verbose_name_plural = 'Antecedentes quirurgicos'
        default_permissions = []

    def __str__(self):
        return '%s' % (self.id)

class MedicacionActual(models.Model): #En el diagrama esta minuscula otras clases entidades mayusculas
    #default id
    nombre_medicamento = models.CharField(max_length=100, unique=False)
    nombre_comercial_me = models.CharField(max_length=200, blank=True, null=True)
    concentracion = models.CharField(max_length=200, blank=True, null=True)
    frecuencia = models.CharField(max_length=200)
    tipo_administracion = models.CharField(max_length=200) #en otro modelo se llama via administracion el de Medicamento
    id_antecedente_personal = models.ForeignKey(AntecedentesPersonal, on_delete=models.CASCADE, db_column='id_antecedentes_personal')


    class Meta:
        db_table = 'Medicacion_actual'
        verbose_name = 'Medicacion actual'
        verbose_name_plural = 'Medicaciones actuales'
        default_permissions = []

    def __str__(self):
        return '%s' % (self.id)

templates/antecedentes/antecedentes_familiares.html
<!--Inicio de la pestaña para antecedentes familiares-->
<div class="tab-pane fade" id="custom-tabs-three-anteFamiliar" role="tabpanel"
    aria-labelledby="custom-tabs-three-anteFamiliar-tab">
    <div class="card-body m">
        <div class="row">
            <div class="col-12">
                <p>
                    <button class="btn btn-outline-info dropdown-toggle dropdown-icon" type="button"
                        data-toggle="collapse" data-target="#formulario_fam" aria-expanded="false">
                        <span aria-hidden="true"></span> Agregar Antecedentes Familiares &nbsp;
                    </button>
                </p>
                <div class="collapse" id="formulario_fam">
                    <!--Form para agregar Familiar-->
                    <form action="{% url 'ante_familiar_crear' paciente.id%}" method="post"
                        name="formuIngresarAntecedentesFam">
                        {% csrf_token %}
                        <div class="card card-info card-outline border-info mb-3 col-lg-10 offset-lg-1">
                            <!-- Inicio del card que engloba los campos del form -->
                            <div class="card-header">
                                <h5>Nuevo Antecedente Familiar</h5>
                            </div>
                            <div class="card-body">
                                <div class="row form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text ">Nombre del familiar</span>
                                        </div>
                                        <input required type="text" class="form-control" id="nombre_familiar"
                                            name="nombre_familiar"
                                            placeholder="Ingrese el nombre completo del familiar">
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text ">Parentesco</span>
                                        </div>
                                        <input required type="text" class="form-control" id="parentesco"
                                            name="parentesco" placeholder="Ingrese el parentesco con el familiar">
                                    </div>
                                </div>
                                <div class="row form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text ">Padecimientos</span>
                                        </div>
                                        <textarea required class="form-control" id="padecimientos" name="padecimientos"
                                            placeholder="En esta area puede ingresar los padecimientos del familiar"></textarea>
                                    </div>
                                </div>
                                <!-- Inicio Botones-->
                                <div class="row">
                                    <div class="col-lg-4 offset-lg-7 text-right">
                                        <a href="{% url 'indexExpedientes' %}" role="button"
                                            class="btn btn-danger">Cancelar</a>
                                        <button type="submit" id="guardarAntFam" name="guardarAntFam"
                                            class="btn btn-info">Guardar
                                        </button>
                                    </div>
                                </div>
                                <!--Fin Botones-->
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

    <!--Modal para editar Familiar-->
    <div class="container-fluid" class="contenedor_editar">
        {% include 'antecedentes/antecedentes_familiares_editar.html' %}
    </div>

    <!--DataTable de Familiares-->
    <div class="row">
        <div class="col-12">
            <div class="card card-secondary card-outline border-secondary">
                <div class="card-header">
                    <h3 class="card-title">
                        Lista de antecedentes familiares
                    </h3>
                </div>
                <div class="row">
                    <div class="card-body col-12">
                        <div class="table-responsive">
                            <table class="table" id="tableAntecedenteFamiliar" name="tableAntecedenteFamiliar"
                                style="width:100% !important;">
                                <thead class="bg-secondary">
                                    <tr>
                                        <td style="min-width:max-content;">Nombre del familiar</td>
                                        <td>Parentesco</td>
                                        <td>Padecimiento</td>
                                        <td>Opciones</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for familiar in paciente.antecedentesfamiliares_set.all %}
                                    <tr>
                                        <td>{{familiar.nombre_familiar}}</td>
                                        <td>{{familiar.parentesco}}</td>
                                        <td>{{familiar.padecimientos}}</td>
                                        <td>
                                            <button type="button" href="#modal_editar_antfamiliar"
                                                onclick="mostrar_formulario_editar('{{familiar.nombre_familiar}}', '{{familiar.parentesco}}', '{{familiar.padecimientos}}', '{{familiar.id}}')"
                                                data-toggle="modal" id="antfamiliar_editar" name="antfamiliar_editar"
                                                class="btn btn-sm btn-success">Editar</button>
                                            <a href="{% url 'ante_familiar_eliminar' familiar.id %}"
                                                class="btn btn-sm btn-danger">Eliminar</a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/antecedentes/antecedentes_medicos.html
<!--====================================================================================================
                    VISTA QUE POSEE LOS ANTECEDENTES MEDICOS
			ESTA VISTA ESTA INCLUIDA EN LOS ANTECEDENTES PERSONALES
====================================================================================================-->
<div class="card card-secondary card-outline border-secondary collapsed-card">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fas">
                Antecedentes médicos
            </i>
        </h3>
        <div class="card-tools">
            <button type="button" class="btn" data-card-widget="collapse" data-toggle="tooltip" title="Collapse"><i
                    class="fas fa-plus"></i></button>
        </div>
    </div>

    <div class="card-body">
        <div class="col-12">
            <p>
                <button class="btn btn-outline-info dropdown-toggle dropdown-icon" type="button" data-toggle="collapse"
                    data-target="#formulario_med" aria-expanded="false">
                    <span aria-hidden="true"></span> Agregar Antecedentes Médicos &nbsp;
                </button>
            </p>
            <div class="collapse" id="formulario_med">
                <!--Form para agregar antecedente medico-->
                <form action="{% url 'ante_medico_crear' paciente.id%}" method="post"
                    name="formuIngresarAntecedentesMed">
                    {% csrf_token %}
                    <div class="card card-info card-outline border-info mb-3 col-lg-10 offset-lg-1">
                        <!-- Inicio del card que engloba los campos del form -->
                        <div class="card-header">
                            <h5>Nuevo Antecedente Médico</h5>
                        </div>
                        <div class="card-body">
                            <div class="row form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text ">Fecha aproximada</span>
                                    </div>
                                    <input required type="text" placeholder="Ingrese la fecha aproximada"
                                        class="form-control" id="fecha_ante_med" name="fecha_ante_med">
                                    <input type="hidden" id="fecha_ante_med_formato" name="fecha_ante_med_formato"
                                        value="" class="form-control">
                                </div>
                            </div>
                            <div class="row row form-group">
                                <div class="input-group">
                                    <input type="hidden" id="id_cod_ante_med" name="id_cod_ante_med" value="">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Código</span>
                                    </div>
                                    <input required type="text" class="form-control" id="codigo" name="codigo"
                                        placeholder="Ingrese el código.">
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text ">Enfemedad</span>
                                    </div>
                                    <textarea class="form-control" rows="2" maxlength="400" id="enfermedad"
                                        placeholder="Ingrese la enfermedad."></textarea>
                                </div>
                            </div>
                            <!-- Inicio Botones-->
                            <div class="row">
                                <div class="col-lg-4 offset-lg-7 text-right">
                                    <a href="{% url 'indexExpedientes' %}" role="button"
                                        class="btn btn-danger">Cancelar</a>
                                    <button type="button" id="guardarAntMed" name="guardarAntMed"
                                        class="btn btn-info">Guardar</button>
                                </div>
                            </div>
                            <!--Fin Botones-->
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!--Modal para editar antecedentes medicos-->
        <div class="container-fluid" class="contenedor_editar">
            {% include 'antecedentes/antecedentes_medicos_editar.html' %}
        </div>
        <!--DataTable de Antecedentes Medicos-->
        <div class="row">
            <div class="col-12">
                <div class="card card-outline border-secondary ">
                    <div class="card-header">
                        <h3 class="card-title">
                            Listado de Antecedentes Médicos
                        </h3>
                    </div>
                    <div class="row">
                        <div class="card-body col-12">
                            <div class="table-responsive">
                                <table class="table" id="tableAntecedenteMedico" name="tableAntecedenteMedico"
                                    style="width: 100%;">
                                    <thead class="bg-secondary">
                                        <tr>
                                            <td>Código </td>
                                            <td>Enfermedad</td>
                                            <td>Fecha Aproximada</td>
                                            <td>Opciones</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for antemedico in paciente.antecedentespersonal.antecedentesmedicos_set.all %}
                                        <tr>
                                            <td>{{antemedico.id_codigo.id10}}</td>
                                            <td>{{antemedico.id_codigo.dec10}}</td>
                                            <td>{{antemedico.fecha}}</td>
                                            <td>
                                                <button type="button" data-target="#modal_editar_antmedicos"
                                                    data-toggle="modal" id="antmedicos_editar" name="antmedicos_editar"
                                                    onclick="mostrar_formulario_editar_antmedico('{{antemedico.fecha}}', '{{antemedico.id_codigo.id10}}', '{{antemedico.id_codigo.dec10}}', '{{antemedico.id}}','{{antemedico.id_codigo.id}}')"
                                                    class="btn btn-sm btn-success">Actualizar</button>
                                                <a href="{% url 'ante_medico_eliminar' antemedico.id %}"
                                                    class="btn btn-sm btn-danger">Eliminar</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/antecedentes/antecedentes_quirurgicos.html
<!--====================================================================================================
                    VISTA QUE POSEE LOS ANTECEDENTES QUIRURGICOS
			ESTA VISTA ESTA INCLUIDA EN LOS ANTECEDENTES PERSONALES
====================================================================================================-->
<br>
<div class="card card-secondary card-outline border-secondary collapsed-card">
    <div class="card-header">
        <h3 class="card-title">
            <i class="fas">
                Antecedentes quirúrgicos
            </i>
        </h3>
        <div class="card-tools">

            <button type="button" class="btn" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-plus"></i>
            </button>
        </div>
    </div>

    <div class="card-body">

        <div class="col-12">
            <p>
                <button class="btn btn-outline-info dropdown-toggle dropdown-icon" type="button" data-toggle="collapse"
                    data-target="#formulario_quirur" aria-expanded="false">
                    <span aria-hidden="true"></span> Agregar Antecedentes Quirúrgicos &nbsp;
                </button>
            </p>
            <div class="collapse" id="formulario_quirur">
                <!--Form para agregar antecedente quirurgico-->
                <form action="{% url 'ante_quirurgico_crear' paciente.id%}" method="post"
                    name="formuIngresarAntecedentesQui">
                    {% csrf_token %}
                    <div class="card card-info card-outline border-info mb-3 col-lg-10 offset-lg-1">
                        <!-- Inicio del card que engloba los campos del form -->
                        <div class="card-header">
                            <h5>Nuevo Antecedente Quirúrgico</h5>
                        </div>
                        <div class="card-body">
                            <div class="row form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text ">Fecha aproximada</span>
                                    </div>
                                    <input required type="text" placeholder="Ingrese la fecha aproximada"
                                        class="form-control" id="fecha_ante_quirur" name="fecha_ante_quirur">
                                    <input type="hidden" id="fecha_ante_quirur_formato" name="fecha_ante_quirur_formato"
                                        value="" class="form-control">
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text ">Descripción</span>
                                    </div>
                                    <textarea required type="text" class="form-control" id="descripcion_cirugia"
                                        name="descripcion_cirugia" placeholder="Ingresar descripción"></textarea>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text ">Causa</span>
                                    </div>
                                    <textarea required type="text" class="form-control" id="causa" name="causa"
                                        placeholder="Ingresar la causa de la intervención quirúrgica"></textarea>
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text ">Complicación</span>
                                    </div>
                                    <textarea required type="text" class="form-control" id="complicacion"
                                        name="complicacion" placeholder="Ingresar complicación"></textarea>
                                </div>
                            </div>
                            <!-- Inicio Botones-->
                            <div class="row">
                                <div class="col-lg-4 offset-lg-7 text-right">
                                    <a href="{% url 'indexExpedientes' %}" role="button"
                                        class="btn btn-danger">Cancelar</a>
                                    <button type="submit" id="guardarAntQuirurgico" name="guardarAntQuirurgico"
                                        class="btn btn-info">Guardar</button>
                                </div>
                            </div>
                            <!--Fin Botones-->
                        </div>
                    </div>
                </form>

            </div>
        </div>

        <!--Modal para editar Antecedentes Quirurgicos-->
        <div class="container-fluid" class="contenedor_editar">
            {% include 'antecedentes/antecedentes_quirurgicos_editar.html' %}
        </div>

        <!--DataTable de Antecedentes Quirurgicos-->
        <div class="card card-outline border-secondary mb-3 ">
            <div class="card-header">
                <h5>Listado de Antecedentes Quirurgicos</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table" id="tableAntecedenteQuirurgico" name="tableAntecedenteQuirurgico"
                        style="width: 100%;">
                        <thead class="bg-secondary">
                            <tr>
                                <td>Fecha</td>
                                <td>Descripción </td>
                                <td>Opciones</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for antequirurgico in paciente.antecedentespersonal.antecedentesquirurgico_set.all %}
                            <tr>
                                <td>{{antequirurgico.fecha}}</td>
                                <td>{{antequirurgico.descripcion_cirugia}}</td>
                                <td>
                                    <button type="button" href="#modal_editar_antquirurgico" data-toggle="modal"
                                        id="antquirurgico_editar" name="antquirurgico_editar"
                                        class="btn btn-sm btn-success"
                                        onclick="mostrar_formulario_editar_antquirurgico('{{antequirurgico.fecha}}', '{{antequirurgico.descripcion_cirugia}}', '{{antequirurgico.causa}}','{{antequirurgico.complicacion}}', '{{antequirurgico.id}}')">Actualizar</button>
                                    <a href="{% url 'ante_quirurgico_eliminar' antequirurgico.id %}"
                                        class="btn btn-sm btn-danger">Eliminar</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>